HelloWorld/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('learning_logs/', include('learning_logs.urls')),
    path('', include('Hello_World.urls')),
]

Hello_World/urls.py
from django.urls import path
from . import views

app_name = 'Hello_World'

urlpatterns = [
    path('', views.index, name='index'),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics')
]

Hello_World/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models

class Topic(models.Model):
    """内容的主题"""
    text = models.CharField(max_length=200)
    data_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """某个主题的具体内容"""
    topic = models.ForeignKey(
        Topic, 
        models.SET_NULL,
        blank=True,
        null=True,
    )
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else: 
            return self.text

Hello_World/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    "主页"
    return render(request, 'Hello_world/index.html')

learning_logs/views.py
from django.shortcuts import render

from .models import Topic

def index(request):
   """学习笔记的主页"""
   return render(request, 'learning_logs/index.html')

def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.order_by('data_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

templates/Hello_World/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello_World</title>
  </head>
  <body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    </p>

    {% block content %}{% endblock %}
  </body>
</html>

templates/Hello_World/index.html
{% extends "Hello_world/base.html" %}

{% block content %}
    <p>Hello, 这是这个项目的主页。</p>
{% endblock %}

templates/learning_logs/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Learning logs</title>
  </head>
  <body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    </p>

    {% block content %}{% endblock %}
  </body>
</html>

templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Learning Log helps you keep track of your lerning, for any topic you're learning about.</p>
{% endblock %}